import React from "react";
import { DataGrid as MUIDataGrid } from "@mui/x-data-grid";

const DataGrid = ({
  column,
  apiRef,
  ariaLabel,
  ariaLabelledBy,
  autoHeight,
  autoPageSize,
  autosizeOnMount,
  autosizeOptions,
  cellModesModel,
  checkboxSelection,
  classes,
  clipboardCopyCellDelimiter,
  columnBufferPx,
  columnGroupHeaderHeight,
  columnHeaderHeight,
  columnVisibilityModel,
  density,
  disableAutosize,
  disableColumnFilter,
  disableColumnResize,
  disableColumnSelector,
  disableColumnSorting,
  disableDensitySelector,
  disableEval,
  disableMultipleRowSelection,
  disableRowSelectionOnClick,
  disableVirtualization,
  editMode,
  estimatedRowCount,
  experimentalFeatures,
  filterDebounceMs,
  filterMode,
  filterModel,
  getCellClassName,
  getDetailPanelContent,
  getEstimatedRowHeight,
  getRowClassName,
  getRowHeight,
  getRowId,
  getRowSpacing,
  hideFooter,
  hideFooterPagination,
  hideFooterSelectedRowCount,
  ignoreDiacritics,
  ignoreValueFormatterDuringExport,
  indeterminateCheckboxAction,
  initialState,
  isCellEditable,
  isRowSelectable,
  keepNonExistentRowsSelected,
  loading,
  localeText,
  logger,
  logLevel,
  nonce,
  onCellClick,
  onCellDoubleClick,
  onCellEditStart,
  onCellEditStop,
  onCellKeyDown,
  onCellModesModelChange,
  onClipboardCopy,
  onColumnHeaderClick,
  onColumnHeaderDoubleClick,
  onColumnHeaderEnter,
  onColumnHeaderLeave,
  onColumnHeaderOut,
  onColumnHeaderOver,
  onColumnOrderChange,
  onColumnResize,
  onColumnResizeEnd,
  onColumnResizeStart,
  onColumnRowDragEnd,
  onColumnRowDragEnter,
  onColumnRowDragLeave,
  onColumnRowDragMove,
  onColumnRowDragStart,
  onColumnSortModelChange,
  onColumnVisibilityModelChange,
  onDensityChange,
  onEditRowsModelChange,
  onFilterModelChange,
  onGridReady,
  onPageSizeChange,
  onSelectionModelChange,
  onSortModelChange,
  pageSizeOptions,
  paginationMeta,
  paginationMode,
  paginationModel,
  processRowUpdate,
  resizeThrottleMs,
  rowBufferPx,
  rowCount,
  rowHeight,
  rowModesModel,
  rowPositionsDebounceMs,
  rows,
  rowSelection,
  rowSelectionModel,
  rowSpacingType,
  scrollbarSize,
  showCellVerticalBorder,
  showColumnVerticalBorder,
  slotProps,
  slots,
  sortingMode,
  sortingOrder,
  sortModel,
  sx,
  unstable_rowSpanning,
  ...props
}) => {
  return (
    <MUIDataGrid
      columns={column}
      apiRef={apiRef}
      aria-label={ariaLabel}
      aria-labelledby={ariaLabelledBy}
      autoHeight={autoHeight}
      autoPageSize={autoPageSize}
      autosizeOnMount={autosizeOnMount}
      autosizeOptions={autosizeOptions}
      cellModesModel={cellModesModel}
      checkboxSelection={checkboxSelection}
      classes={classes}
      clipboardCopyCellDelimiter={clipboardCopyCellDelimiter}
      columnBuffer={columnBufferPx}
      columnGroupHeaderHeight={columnGroupHeaderHeight}
      columnHeaderHeight={columnHeaderHeight}
      columnVisibilityModel={columnVisibilityModel}
      density={density}
      disableAutosize={disableAutosize}
      disableColumnFilter={disableColumnFilter}
      disableColumnResize={disableColumnResize}
      disableColumnSelector={disableColumnSelector}
      disableColumnSorting={disableColumnSorting}
      disableDensitySelector={disableDensitySelector}
      disableEval={disableEval}
      disableMultipleRowSelection={disableMultipleRowSelection}
      disableRowSelectionOnClick={disableRowSelectionOnClick}
      disableVirtualization={disableVirtualization}
      editMode={editMode}
      estimatedRowCount={estimatedRowCount}
      experimentalFeatures={experimentalFeatures}
      filterDebounceMs={filterDebounceMs}
      filterMode={filterMode}
      filterModel={filterModel}
      getCellClassName={getCellClassName}
      getDetailPanelContent={getDetailPanelContent}
      getEstimatedRowHeight={getEstimatedRowHeight}
      getRowClassName={getRowClassName}
      getRowHeight={getRowHeight}
      getRowId={getRowId}
      getRowSpacing={getRowSpacing}
      hideFooter={hideFooter}
      hideFooterPagination={hideFooterPagination}
      hideFooterSelectedRowCount={hideFooterSelectedRowCount}
      ignoreDiacritics={ignoreDiacritics}
      ignoreValueFormatterDuringExport={ignoreValueFormatterDuringExport}
      indeterminateCheckboxAction={indeterminateCheckboxAction}
      initialState={initialState}
      isCellEditable={isCellEditable}
      isRowSelectable={isRowSelectable}
      keepNonExistentRowsSelected={keepNonExistentRowsSelected}
      loading={loading}
      localeText={localeText}
      logger={logger}
      logLevel={logLevel}
      nonce={nonce}
      onCellClick={onCellClick}
      onCellDoubleClick={onCellDoubleClick}
      onCellEditStart={onCellEditStart}
      onCellEditStop={onCellEditStop}
      onCellKeyDown={onCellKeyDown}
      onCellModesModelChange={onCellModesModelChange}
      onClipboardCopy={onClipboardCopy}
      onColumnHeaderClick={onColumnHeaderClick}
      onColumnHeaderDoubleClick={onColumnHeaderDoubleClick}
      onColumnHeaderEnter={onColumnHeaderEnter}
      onColumnHeaderLeave={onColumnHeaderLeave}
      onColumnHeaderOut={onColumnHeaderOut}
      onColumnHeaderOver={onColumnHeaderOver}
      onColumnOrderChange={onColumnOrderChange}
      onColumnResize={onColumnResize}
      onColumnResizeEnd={onColumnResizeEnd}
      onColumnResizeStart={onColumnResizeStart}
      onColumnRowDragEnd={onColumnRowDragEnd}
      onColumnRowDragEnter={onColumnRowDragEnter}
      onColumnRowDragLeave={onColumnRowDragLeave}
      onColumnRowDragMove={onColumnRowDragMove}
      onColumnRowDragStart={onColumnRowDragStart}
      onColumnSortModelChange={onColumnSortModelChange}
      onColumnVisibilityModelChange={onColumnVisibilityModelChange}
      onDensityChange={onDensityChange}
      onEditRowsModelChange={onEditRowsModelChange}
      onFilterModelChange={onFilterModelChange}
      onGridReady={onGridReady}
      onPageSizeChange={onPageSizeChange}
      onSelectionModelChange={onSelectionModelChange}
      onSortModelChange={onSortModelChange}
      pageSizeOptions={pageSizeOptions}
      paginationMeta={paginationMeta}
      paginationMode={paginationMode}
      paginationModel={paginationModel}
      processRowUpdate={processRowUpdate}
      resizeThrottleMs={resizeThrottleMs}
      rowBuffer={rowBufferPx}
      rowCount={rowCount}
      rowHeight={rowHeight}
      rowModesModel={rowModesModel}
      rowPositionsDebounceMs={rowPositionsDebounceMs}
      rows={rows}
      rowSelection={rowSelection}
      rowSelectionModel={rowSelectionModel}
      rowSpacingType={rowSpacingType}
      scrollbarSize={scrollbarSize}
      showCellVerticalBorder={showCellVerticalBorder}
      showColumnVerticalBorder={showColumnVerticalBorder}
      slotProps={slotProps}
      slots={slots}
      sortingMode={sortingMode}
      sortingOrder={sortingOrder}
      sortModel={sortModel}
      sx={sx}
      unstable_rowSpanning={unstable_rowSpanning}
      {...props}
    />
  );
};

export default DataGrid;
